Impl separate REST API for entry node.
iotaledger/bee pull request #1109
Opened 2022-02-08 13:24 UTC by rufsam

2022-02-08 14:58 UTC, thibault-martinez requested changes
You should also call the init in the entrymode

2022-02-08 16:31 UTC, pvdrz approved these changes, later dismissed

2022-02-09 09:54 UTC, Alex6323 approved these changes, later dismissed

2022-02-09 12:38 UTC, grtlr approved these changes, later dismissed

2022-02-09 13:31 UTC, grtlr submitted a review, later dismissed

2022-02-09 13:49 UTC, Adam-Gleave approved these changes, later dismissed

2022-02-09 13:58 UTC, thibault-martinez commented on bee-api/bee-rest-api/src/endpoints/mod.rs
> +#[async_trait]
```suggestion

#[async_trait]
```

2022-02-09 14:08 UTC, thibault-martinez commented on bee-api/bee-rest-api/src/endpoints/mod.rs
>  #[async_trait]
```suggestion

#[async_trait]
```

2022-02-09 14:14 UTC, thibault-martinez approved these changes

2022-02-09 14:22 UTC, grtlr approved these changes

2022-02-09 17:17 UTC, pvdrz approved these changes

2022-02-09 18:15 UTC, merged