Bump API version from `v1` to `v2`
iotaledger/bee pull request #1146
Opened 2022-02-17 13:59 UTC by rufsam

Fixes https://github.com/iotaledger/bee/issues/1107

2022-02-17 15:21 UTC, grtlr submitted a review, later dismissed

2022-02-17 15:21 UTC, grtlr commented on bee-api/bee-rest-api/CHANGELOG.md
> +- Bump API version from `v1` to `v2`
```suggestion
- Bump API version from `v1` to `v2`;

```

2022-02-17 16:17 UTC, Adam-Gleave approved these changes, later dismissed

2022-02-17 16:54 UTC, pvdrz approved these changes, later dismissed

2022-02-17 17:45 UTC, thibault-martinez approved these changes

2022-02-17 17:46 UTC, thibault-martinez requested changes
There are still instances of `v1` in config.rs and responses.rs

2022-02-18 11:22 UTC, pvdrz approved these changes, later dismissed

2022-02-21 08:34 UTC, thibault-martinez requested changes
The routes of the `reverse_proxy_filter` in the dashboard also needs to be adapted to v2.

2022-02-21 14:10 UTC, grtlr approved these changes

2022-02-21 14:37 UTC, Adam-Gleave approved these changes

2022-02-21 15:24 UTC, pvdrz approved these changes

2022-02-21 20:16 UTC, thibault-martinez approved these changes

2022-02-21 20:17 UTC, merged