feat(ternary) use i128/u128 only when cfg(has_i128)
iotaledger/bee pull request #138
Opened 2020-11-04 18:16 UTC by lucasfernog

# Description of change

Changes required so bee-ternary can compile on ESP32 targets.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Compiling to ESP32.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have checked that new and existing unit tests pass locally with my changes

2020-11-04 18:22 UTC, thibault-martinez requested changes
Thanks! Can you add a little line in the "unreleased" section of the changelog please ? To not forget about this for an upcoming release :)

2020-11-05 10:49 UTC, zesterer approved these changes, later dismissed

2020-11-05 19:23 UTC, lucasfernog commented
done @thibault-martinez

2020-11-06 16:49 UTC, thibault-martinez approved these changes

2020-11-06 16:57 UTC, Alex6323 approved these changes

2020-11-06 17:05 UTC, zesterer approved these changes

2020-11-06 17:05 UTC, merged