Fixing and cleanup of inx feature gate
iotaledger/bee pull request #1517
Opened 2022-09-19 09:46 UTC by Alex6323

# Description of change

Bugfix:
* Explicitly marks `inx` feature as dependent on `std` (compilation of `bee-block` failed on `cargo c --features inx`)

Enhancements:
* Removes the package renaming to `inx-binding` as it's not really necessary
* Uses latest `inx` version (beta.8)
* Reorders `bee-inx` keywords
* Removes unnecessary dev dependency

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

2022-09-19 11:35 UTC, Thoralf-M commented on bee-inx/Cargo.toml
> +keywords = [ "iota", "inx", "bee", "node", "plugin" ]
What's the reason for this re(un)order? :trollface:

2022-09-19 11:38 UTC, Thoralf-M requested changes
![image](https://user-images.githubusercontent.com/46689931/191008931-fa62848c-b4b0-4d15-ae91-e4557a8b6061.png)

2022-09-19 13:22 UTC, Alex6323 commented on bee-inx/Cargo.toml
> +keywords = [ "iota", "inx", "bee", "node", "plugin" ]
personal preference :trollface: 

more serious...from general to specific.

2022-09-27 07:14 UTC, grtlr approved these changes

2022-09-27 07:15 UTC, thibault-martinez approved these changes

2022-09-27 07:15 UTC, merged