Switch to rumqttd MQTT broker
iotaledger/bee pull request #459
Opened 2021-03-15 09:09 UTC by Alex6323

2021-03-16 13:05 UTC, thibault-martinez requested changes
Format :)

2021-03-29 10:23 UTC, thibault-martinez commented on bee-node/src/plugins/mqtt/mod.rs
> +        // **Note**: 'start' creates a custom tokio runtime and blocks until ctrl-c is detected.
Can we ask them if there is any alternative ? Or if they'd consider offering one ?

2021-04-07 13:05 UTC, thibault-martinez commented on bee-node/Cargo.toml
> +#paho-mqtt = { version = "0.9", default-features = false, features = ["bundled"]}
Remove :)

2021-08-04 09:40 UTC, Alex6323 commented
Closed in favor of an upcoming PR by @rufsam

2021-08-04 09:40 UTC, closed without merging