Add console.md to spec documentation
iotaledger/bee pull request #591
Opened 2021-05-19 15:32 UTC by Adam-Gleave

# Description of change

Add `console.md` to `/docs/dev/specs`, describing the use of the `console` feature.

## Type of change
- Documentation Fix

2021-05-20 07:31 UTC, thibault-martinez commented
Can you rename it to `tokio-console.ms` please ?

2021-05-20 08:30 UTC, Adam-Gleave commented
Done 👍

2021-05-20 08:38 UTC, thibault-martinez reviewed
I would probably add a little bit of context. Why is this a nice feature ? What can we do with it that we can't do without ? etc

2021-05-20 09:38 UTC, Adam-Gleave commented
Should have more context into why we want this feature now and what it can do for us. Let me know if there's anything else specific that you want to see.

2021-05-20 13:01 UTC, NemesisFLX submitted a review, later dismissed

2021-05-20 13:44 UTC, johanneskeim submitted a review, later dismissed

2021-05-20 13:48 UTC, Critical94 commented on docs/dev/specs/tokio-console.md
> +The `console` feature provides instrumentation on all tasks spawned in the `BeeNode::spawn` method, and aggregates information provided by this insrumentation in a "subscriber", that allows logging a
Typo insrumentation -> instrumentation

2021-05-20 14:34 UTC, Adam-Gleave commented on docs/dev/specs/tokio-console.md
> +The `console` feature provides instrumentation on all tasks spawned in the `BeeNode::spawn` method, and aggregates information provided by this insrumentation in a "subscriber", that allows logging a
Fixed, thanks!

2021-05-21 14:51 UTC, pvdrz approved these changes, later dismissed

2021-05-24 09:37 UTC, thibault-martinez requested changes

2021-05-24 09:37 UTC, thibault-martinez commented on docs/dev/specs/tokio-console.md
> +The `bee-node` crate now includes a `console` feature, which can help with debugging and providing diagnostics for the multiple async tasks that Bee is executing at any given time. Building with this
```suggestion
The `bee-node` crate includes a `console` feature, which can help with debugging and providing diagnostics for the multiple async tasks that Bee is executing at any given time. Building with this feature enabled and running a separate executable will provide realtime diagnostics in your terminal. 
```

2021-05-24 09:37 UTC, thibault-martinez commented on docs/dev/specs/tokio-console.md
> +The `bee-node` crate now includes a `console` feature, which can help with debugging and providing diagnostics for the multiple async tasks that Bee is executing at any given time. Building with this
```suggestion
The `bee-node` crate now includes a `console` feature, which can help with debugging and providing diagnostics for the multiple async tasks that the node is executing at any given time. Building with this feature enabled and running a separate executable will provide realtime diagnostics in your terminal. 
```

2021-05-24 09:37 UTC, thibault-martinez commented on docs/dev/specs/tokio-console.md
> +The `console` feature provides instrumentation on all tasks spawned in the `BeeNode::spawn` method, and aggregates information provided by this instrumentation in a "subscriber", that allows logging
Only tasks spawned in `BeeNode::spawn` ?

2021-05-24 09:37 UTC, thibault-martinez commented on docs/dev/specs/tokio-console.md
> +The `console` feature provides instrumentation on all tasks spawned in the `BeeNode::spawn` method, and aggregates information provided by this instrumentation in a "subscriber", that allows logging
You use both `realtime` and `real-time`, align!

2021-05-24 09:37 UTC, thibault-martinez commented on docs/dev/specs/tokio-console.md
> +```
I would maybe combine the two previous sentences and the following command `RUSTFLAGS="--cfg tokio_unstable" cargo run --release --features console`

2021-05-24 09:37 UTC, thibault-martinez commented on docs/dev/specs/tokio-console.md
> +.../tokio-console/console/ > cargo run
For some reason it took me a while to understand that the `>` is not a redirection. Maybe use the standard `$` to indicate start of the command.

2021-05-26 08:42 UTC, Adam-Gleave commented on docs/dev/specs/tokio-console.md
> +The `console` feature provides instrumentation on all tasks spawned in the `BeeNode::spawn` method, and aggregates information provided by this instrumentation in a "subscriber", that allows logging
Yep, there's a little boilerplate so currently it's all contained here. This way all worker tasks can be instrumented from one place. There are a couple extra tasks spawned in the node, but all look to be nested within these worker tasks -- nested tasks can also trigger the deadlock we're seeing.

2021-05-26 09:03 UTC, thibault-martinez approved these changes

2021-05-26 09:03 UTC, merged