Update with style guide
iotaledger/bee pull request #649
Opened 2021-06-30 08:54 UTC by lucas-tortora

# Description of change
As part of the effort to update, stylize and unify all documentation at a central docs/wiki site, the Ecosystem team is in the process of reviewing all our current documentation. With this goal in mind, we would like to  modify and/or expand the documentation.  

At the moment, the Bee docs are missing some information, this is just a minor improvement and styling.  

@thibault-martinez, I've included the new information on nodes and API reference and other improvements we discussed, but before we move forward I think someone with in depth knowledge should review everything I've "imported" from the Hornet docs, as well as all the TO-DOs (there's one in in the crate overview and most of the storage table in the configuration section).

## Links to any relevant issues

https://github.com/iotaledger/docs.iota.org/issues/13

## Type of change

- Documentation Fix

## How the change has been tested

There shouldn't be any functional changes, only documentation style.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation

2021-07-02 04:41 UTC, charlesthompson3 approved these changes, later dismissed
LGTM!

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/code_of_conduct.md
> +- Publishing others' private information, such as a physical or electronic  address, without explicit permission.
```suggestion
- Publishing others' private information, such as a physical or electronic address, without explicit permission.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/code_of_conduct.md
> +- Other conduct which could reasonably be considered inappropriate in a  professional setting.
```suggestion
- Other conduct which could reasonably be considered inappropriate in a professional setting.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/code_of_conduct.md
> +This Code of Conduct applies within all project spaces.  It also applies when an individual is representing the project or its community in public spaces. Examples of representing a project or commun
```suggestion
This Code of Conduct applies within all project spaces. It also applies when an individual is representing the project or its community in public spaces. Examples of representing a project or community include:
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/code_of_conduct.md
> +All complaints will be reviewed, investigated, and will result in a response that  is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality
```suggestion
All complaints will be reviewed, investigated, and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality in regard to the reporter of an incident.  Project maintainers may post details of specific enforcement policies may separately.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/contribution.md
> +- [**StackExchange:**](https://iota.stackexchange.com/) For technical and troubleshooting questions
```suggestion
- [**Developer documentation:**](https://docs.iota.org/) For official information about developing with IOTA technology.
- [**Discord:**](https://discord.iota.org/) For real-time chats with the developers and community members.
- [**IOTA cafe:**](https://iota.cafe/) For technical discussions with the Research and Development Department at the IOTA Foundation.
- [**StackExchange:**](https://iota.stackexchange.com/) For technical and troubleshooting questions.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/contribution.md
> +- Join the Bee Initiative
```suggestion
- Report a bug.
- Suggest a new feature.
- Build a new feature.
- Join the Bee Initiative.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/contribution.md
> +#### Before Reporting a Bug
```suggestion
#### Before reporting a bug
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/contribution.md
> +#### Submitting A Bug Report
```suggestion
#### Submitting a bug report
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/contribution.md
> +To suggest a new feature, talk to the IOTA community and IOTA Foundation members in the #bee-discussion channel on [Discord](https://discord.iota.org/).
```suggestion
#### Before suggesting a new feature

Ensure the feature has not already been suggested by searching on GitHub under [Issues](https://github.com/iotaledger/bee/issues).

#### Suggesting a new feature

To suggest a new feature, talk to the IOTA community and IOTA Foundation members in the #bee-discussion channel on [Discord](https://discord.iota.org/).
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/contribution.md
> +To build a new feature, check out a new branch based on the `master` branch, and be sure to document any public-facing APIs, using Rust code comments.
```suggestion
#### Before building a new feature

Make sure to discuss the feature in the #bee-discussion channel on [Discord](https://discord.iota.org/).

Otherwise, your feature may not be approved at all.

#### Building a new feature

To build a new feature, check out a new branch based on the `master` branch, and be sure to document any public-facing APIs, using Rust code comments.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/contribution.md
> +- To be compatible with the guidelines of the Eclipse foundation, all code must be licensed under the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0). This license must be
```suggestion
### Join the Bee Initiative 

The [Bee Initiative](https://github.com/iota-community/bee) is a collaborative effort to improve the Bee developer experience by focussing on the following goals:

- Quality Assurance and Quality Control
- Documentation
- Benchmarks
- RFCs
- Node usability
- Improvements to modules and libraries

## How Much Time Should I Invest?

You can invest as much, or as little, time as you want into the initiative.

## What's in it for You?

In return for your time, you will get to be a part of the future of IOTA technology. As well, you will also be given a badge on Discord to show others that you are a valuable member of the IOTA community.

## How to Join

If you're interested in joining, drop us a line in the #experience channel on [Discord](https://discord.iota.org/).

## Pull Requests 

This section guides you through submitting a pull request (PR). Following these guidelines helps give your PR the best chance of being approved and merged.

### Before Submitting a Pull Request

Before submitting a pull request, please follow these steps to have your contribution considered by the maintainers:

- A pull request should have exactly one concern (for example one feature or one bug). If a PR addresses more than one concern, it should be split into two or more PRs.

- A pull request can be merged only if it references an open issue.

:::info  
You don't need to open an issue for minor changes such as typos.
:::

- All public interfaces should have descriptive documentation, including an
example that compiles and passes the [documentation tests](https://doc.rust-lang.org/rustdoc/documentation-tests.html).

- All instances of `unsafe` should have a comment that explains why its use was unavoidable.

- All code should be well tested, using unit and integration tests.

- Code must compile and pass our [continuous integration tests](../../.github/workflows).

- To be compatible with the guidelines of the Eclipse foundation, all code must be licensed under the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0). This license must be referenced in every crate of the workspace (add [`./LICENSE`] to the crate's top level directory). For Rust crates, every `Cargo.toml` must contain the line `license = "Apache-2.0"`.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/contribute/security_vulnerabilities.md
> +We sincerely appreciate the efforts of security researchers in keeping our community safe.
```suggestion
- Out of concern for the availability of our services to all users, please do not attempt to carry out DoS attacks, leverage black hat SEO techniques, spam people, or other similarly questionable things. We also discourage the use of any vulnerability testing tools that automatically generate significant volumes of traffic.
    
## What We Promise:

- We will respond to your report within 3 business days with our evaluation of the report, and an expected resolution date.
- If you have followed the instructions above, we will not take any legal action against you in regard to the report.
- We will keep you informed during all stages of resolving the problem.
- To show our appreciation for your effort and cooperation during the report, we will list your name, and a link to a personal website/social network profile on the page below.  This way the public can know you've helped keep the IOTA Foundation secure.

We sincerely appreciate the efforts of security researchers in keeping our community safe.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/getting_started/getting_started.md
> +the [config.toml](configuration.md) file.
```suggestion
The mentioned ports are important for flawless node operation. The REST HTTP API port is optional and is only needed if you want to offer access to your node's API. All ports can be customized inside the [config.toml](configuration.md) file.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/getting_started/nodes_101.md
> +To distribute the messages across the rest of the network, nodes synchronize their local databases with their neighbors.
```suggestion
# Nodes 101

The IOTA network is a distributed type of network called Tangle. The network is distributed among plenty of servers
called nodes. Nodes are the backbone of an IOTA network. This section covers what nodes do in an IOTA network.

Nodes are responsible for:

- Providing an API to interact with the Tangle/IOTA network.
- Validating [messages]((https://chrysalis.docs.iota.org/guides/dev_guide.html#messages-payloads-and-transactions)) and ledger mutations for consistency.
- Providing data for other nodes to synchronize to the latest state of the network.

## Attaching New Messages to the Tangle

A _message_ is a data structure that is actually being broadcast in the IOTA network and represents a vertex in the
Tangle graph. When nodes receive a new message, they attach it to the Tangle by adding the message to their local database.

As a result, at any point in time, all nodes may have different messages in their local databases. These messages make up a node's view of the Tangle.

To distribute the messages across the rest of the network, nodes synchronize their local databases with their neighbors.
```

2021-07-02 04:41 UTC, charlesthompson3 commented on docs/getting_started/nodes_101.md
> +* Once the node has confirmed a transaction with the Tangle, update the node's record of balances .
```suggestion
## Synchronizing With the Rest of the Network

Like any distributed system, nodes in an IOTA network synchronize their databases with other nodes called neighbors to form a single source of truth.

When one node, no matter where it is in the world, receives a message, it will try to _gossip_ it to all its neighbors. This way, all nodes will eventually see all the messages, and store them in their local databases.

To synchronize, nodes in IOTA networks use milestones. If the node has the history of messages that a milestone references, that milestone is solid. Therefore, nodes know if they are synchronized if the index of their latest solid milestone is the same as the index of the latest milestone that it has received.

When a node is synchronized, it then has enough information to decide which transactions it considers confirmed.

## Deciding Which Messages Are Confirmed

All messages remain in a pending state until the node is sure of their validity. For a definition of a message, see [Messages, payloads, and transactions](https://chrysalis.docs.iota.org/guides/dev_guide.html#messages-payloads-and-transactions).

Even when a message is valid, there are situations in which nodes may not be able to make a decision, like in the case of a double spend.

When nodes detect double spends, they must decide which message to consider confirmed and which one to ignore. Nodes do this by using consensus rules that are built into their node software using a network protocol.

## Keeping a Record of the Balances on Addresses Via `UTXO`

All nodes keep a record of the [Unspent Transaction Outputs (UTXO)](https://chrysalis.docs.iota.org/guides/dev_guide.html#unspent-transaction-output-utxo) so they can do the following:

* Check that a transaction is not transferring more IOTA tokens than are available on the address.
* Respond to clients' requests for their balance.
* Once the node has confirmed a transaction with the Tangle, update the node's record of balances . 
```

2021-07-02 08:44 UTC, thibault-martinez reviewed
The following files already exist under in the `.github` folder because GitHub wants you to have them. Can we maybe use them instead of having duplicates ? And edit them if you think they need change ?
- contribute.md
- security_vulnerabilities.md
- code_of_conduct.md

2021-07-19 08:07 UTC, thibault-martinez requested changes

2021-07-19 08:07 UTC, thibault-martinez commented on .github/workflows/deploy_docs_to_gh-pages.yml
> +    branches: [dev, develop, main, master]
```suggestion
    branches: [dev, stable]
```

2021-07-19 08:07 UTC, thibault-martinez commented on .github/workflows/deploy_docs_to_gh-pages.yml
> +    branches: [dev, develop, main, master]
```suggestion
    branches: [dev, stable]
```

2021-07-19 08:09 UTC, thibault-martinez requested changes
We do not use uppercases in folders in a Rust repository. I would appreciate if we can rename `docOps` to `docs`, even if it means having `docs/docs`, I think it's fine.

2021-07-19 14:51 UTC, lucas-tortora commented
> We do not use uppercases in folders in a Rust repository. I would appreciate if we can rename `docOps` to `docs`, even if it means having `docs/docs`, I think it's fine.

I've updated the directory name, and the GH action accordingly :)

2021-07-19 15:59 UTC, thibault-martinez commented on .github/workflows/deploy-docs-to-gh-pages.yml
> +  pull_request:
I'm not so sure about this workflow running on pull request. IMO it should be ran only once on pushes on the said branches.

2021-07-19 16:06 UTC, thibault-martinez commented on documentation/docs/welcome.md
> +# A Framework For Building IOTA Nodes, Clients, and Applications in Rust
Is this basically just the README ? Can we include it instead ?

2021-07-20 07:36 UTC, thibault-martinez approved these changes

2021-07-20 07:52 UTC, merged