Add the plugin manager
iotaledger/bee pull request #665
Opened 2021-07-12 20:46 UTC by pvdrz

2021-07-13 08:40 UTC, thibault-martinez requested changes

2021-07-13 08:40 UTC, thibault-martinez commented on bee-node/Cargo.toml
> +notify = { version = "4.0" }
```suggestion
notify = "4.0"
```

2021-07-13 08:40 UTC, thibault-martinez commented on bee-node/src/lib.rs
> +pub use banner::print_logo_and_version;
Why ?

2021-07-13 08:40 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +use notify::{watcher, DebouncedEvent, RecommendedWatcher, RecursiveMode, Watcher};
3rd parties before std

2021-07-13 14:37 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +        println!("loading plugin \"{}\"", path.display());
Can you use the logger instead ?

2021-07-13 15:14 UTC, thibault-martinez requested changes

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/mod.rs
> +//! The bee plugin system.
```suggestion
//! The bee node plugin system.
```

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +//! The bee plugin manager.
```suggestion
//! The bee node plugin manager.
```

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +    /// Create a new plugin manager.
```suggestion
    /// Creates a new plugin manager.
```

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +    /// Listen for changes in the plugins folder and loads every new plugin found in it.
```suggestion
    /// Listens for changes in the plugins folder and loads every new plugin found in it.
```

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +                        info!("plugin \"{}\" could not be loaded: {}", path.display(), err);
```suggestion
                        warn!("plugin \"{}\" could not be loaded: {}", path.display(), err);
```

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +                | DebouncedEvent::Remove(_) => (),
Why not _ ?

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +                DebouncedEvent::Rescan => {
When is that triggered ?

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +        info!("plugin \"{}\" loaded with PID {}", path.display(), child.id());
```suggestion
        debug!("plugin \"{}\" loaded with PID {}", path.display(), child.id());
```

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +        assert!(self.plugins.insert(path.to_owned(), child).is_none());
A little comment why we think this is never going to panic would be nice

2021-07-13 15:14 UTC, thibault-martinez commented on bee-node/src/plugin/manager.rs
> +        info!("killing plugin \"{}\"", path.display());
I would put an unloading log in the other method rather than a killing load, for consistency

2021-07-16 16:27 UTC, pvdrz commented
I think the design at https://github.com/iotaledger/bee/pull/668 is a bit better so I'm closing this PR in favor of the other one.

2021-07-16 16:27 UTC, closed without merging