`bee-message` tests
iotaledger/bee pull request #700
Opened 2021-08-13 12:43 UTC by Adam-Gleave

More test coverage for `bee-message`. Opening now so I can see the coverage info through the workflow, but not done yet.

2021-08-18 16:50 UTC, thibault-martinez requested changes

2021-08-18 16:50 UTC, thibault-martinez commented on bee-message/tests/indexation_payload.rs
> +    println!("{:?}", IndexationPayload::unpack_from_slice(bytes.clone()));
Remove

2021-08-18 16:50 UTC, thibault-martinez commented on bee-message/tests/payload.rs
> +fn application_message_payload_round_trip() {
Can you use suffix `packable_round_trip` for all these ?

2021-08-18 16:50 UTC, thibault-martinez commented on bee-message/tests/payload.rs
> +fn application_message_payload_round_trip() {
Can you add a packable length test as well in all these ?

2021-08-19 11:12 UTC, Adam-Gleave commented
Not 100% sure what happened with git there, but comments are addressed.

2021-08-19 11:25 UTC, thibault-martinez approved these changes

2021-08-23 09:41 UTC, merged