clone metadata in get()
iotaledger/bee pull request #752
Opened 2021-09-28 16:56 UTC by rufsam

2021-09-28 16:57 UTC, pvdrz approved these changes, later dismissed

2021-09-28 17:07 UTC, Adam-Gleave submitted a review, later dismissed

2021-09-29 07:47 UTC, thibault-martinez requested changes
Fix the CI

2021-09-29 07:47 UTC, thibault-martinez commented on bee-tangle/src/tangle.rs
>      /// Retrieves the [`MessageData`], associated with a [`MessageId`], from the [`Tangle`] .
Wrong comment

2021-09-29 11:37 UTC, thibault-martinez approved these changes

2021-09-29 12:30 UTC, Adam-Gleave approved these changes

2021-09-29 14:02 UTC, pvdrz approved these changes

2021-09-29 14:06 UTC, merged