Automatically check license compatibility
iotaledger/bee pull request #772
Opened 2021-10-12 18:21 UTC by grtlr

# Description of change

Use [`cargo-about`](https://github.com/EmbarkStudios/cargo-about) to automatically check license compatibility.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Checked the number of crates that `cargo-about` gathered against the number of crates in `Cargo.lock`. I also checked if the workflow fails if licenses are left out.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

2021-10-12 18:23 UTC, grtlr commented
We still need to decide which licenses we want to accept. The current set of licenses can be found in `about.toml`. @thibault-martinez what do you think?

2021-10-12 18:25 UTC, thibault-martinez commented
Is that all the licenses we are currently having in our deps ? I would just start with that and add more in the future as they come up and if they are compatible.

2021-10-12 18:31 UTC, grtlr commented
Yes, that's what I'm going with for now. I don't know how these licenses interact though—especially `ISC` and `MPL`.

2021-10-12 19:00 UTC, thibault-martinez commented on about.toml
> +ignore-dev-dependencies = false
Can you maybe put this file in the `.github/workflows` folder please ?

2021-10-13 08:30 UTC, thibault-martinez commented on .github/workflows/about.toml
> +# This is the configuration file that is used by `cargo-about` to check license
As a note for the future, we use a format with 120 columns, including comments. This is not code per se so you don't necessarily have to change here but keep in mind for later ;)

2021-10-13 08:47 UTC, grtlr commented on .github/workflows/about.toml
> +# This is the configuration file that is used by `cargo-about` to check license
Good to know! I have changed the formatting.

2021-10-13 08:49 UTC, thibault-martinez approved these changes

2021-10-13 17:02 UTC, pvdrz submitted a review, later dismissed

2021-10-13 17:05 UTC, Adam-Gleave submitted a review, later dismissed

2021-10-14 08:38 UTC, thibault-martinez requested changes

2021-10-14 08:38 UTC, thibault-martinez commented on .github/workflows/licenses.yml
> +  format:
```suggestion
  licenses:
```
Probably copy-pasted 😬

2021-10-14 08:45 UTC, grtlr commented on .github/workflows/licenses.yml
> +  format:
you bet

2021-10-14 08:50 UTC, thibault-martinez approved these changes

2021-10-14 08:51 UTC, Adam-Gleave approved these changes

2021-10-14 09:19 UTC, merged