Add in-memory storage
iotaledger/bee pull request #778
Opened 2021-10-15 21:03 UTC by pvdrz

# Description of change

Adds the `bee-storage-volatile` crate as an in-memory storage backend.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Running the `bee-storage-test` suite.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

2021-10-18 13:18 UTC, thibault-martinez requested changes

2021-10-18 13:18 UTC, thibault-martinez commented on Cargo.toml
> +    "bee-storage/bee-storage-test",
align!

2021-10-18 13:18 UTC, thibault-martinez commented on bee-storage/bee-storage-volatile/src/storage.rs
> +/// The sled database.
Not sled

2021-10-18 13:18 UTC, thibault-martinez commented on bee-storage/bee-storage-volatile/src/storage.rs
> +
```suggestion
```

2021-10-18 13:18 UTC, thibault-martinez commented on bee-storage/bee-storage-volatile/src/storage.rs
> +use thiserror::Error;
```suggestion

use thiserror::Error;
```

2021-10-18 13:18 UTC, thibault-martinez commented on bee-storage/bee-storage-volatile/src/storage.rs
> +//! The sled storage backend.
Not sled

2021-10-18 13:18 UTC, thibault-martinez commented on bee-storage/bee-storage-volatile/src/lib.rs
> +mod table;
Can you put mod before then a newline please

2021-10-18 13:18 UTC, thibault-martinez commented on bee-storage/bee-storage-volatile/Cargo.toml
> +num_cpus = "1.13"
Add patches please

2021-10-18 13:18 UTC, thibault-martinez commented on bee-storage/bee-storage-volatile/Cargo.toml
> +name = "bee-storage-volatile"
Would it be better called `bee-storage-memory` ? Would better fit the definition you give of it IMO.

2021-10-21 11:12 UTC, thibault-martinez commented on bee-storage/bee-storage-memory/src/access/batch.rs
> +    fn batch_commit(&self, batch: Self::Batch, _durability: bool) -> Result<(), <Self as StorageBackend>::Error> {
This doesn't look atomic ?

2021-10-21 15:21 UTC, pvdrz commented on bee-storage/bee-storage-memory/src/access/batch.rs
> +    fn batch_commit(&self, batch: Self::Batch, _durability: bool) -> Result<(), <Self as StorageBackend>::Error> {
It is atomic for each table, should it be atomic over the whole storage? I think the `sled` backend is not either.

2021-10-21 15:28 UTC, thibault-martinez commented on bee-storage/bee-storage-memory/src/access/batch.rs
> +    fn batch_commit(&self, batch: Self::Batch, _durability: bool) -> Result<(), <Self as StorageBackend>::Error> {
Yeah I just noticed it's not atomic in sled but it definitely should... That's the whole point of the batch

2021-10-21 16:46 UTC, thibault-martinez approved these changes

2021-10-21 20:23 UTC, merged