Remove `chrono`
iotaledger/bee pull request #784
Opened 2021-10-19 12:54 UTC by Adam-Gleave

# Description of change

Removes the `chrono` crate.

I have also created a new `time` module in `bee-common` for getting local time and creating formatted strings, since the same code is used in a couple of different places.

## Links to any relevant issues

#783 and #779.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Run the node to ensure timestamps format correctly. The output shows as:

```
2021-10-19 13:18:54 bee_protocol::workers::message::payload    INFO  Running.
```
This is in the correct local time to me (UTC +1).

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

2021-10-20 15:19 UTC, Adam-Gleave commented
Adding to #786.

2021-10-21 09:24 UTC, thibault-martinez requested changes

2021-10-21 09:24 UTC, thibault-martinez commented on bee-common/bee-common/src/logger/mod.rs
> +use crate::time as time_util;
Can you maybe just use `crate::time::format` directly in the macro and not import it ?

2021-10-21 09:24 UTC, thibault-martinez commented on bee-common/bee-common/src/time.rs
> +// Copyright 2020-2021 IOTA Stiftung
```suggestion
// Copyright 2021 IOTA Stiftung
```

2021-10-21 10:58 UTC, thibault-martinez commented on bee-common/bee-common/src/logger/mod.rs
> +        use crate::time as time_util;
Sorry I meant `crate::time::format` directly, without previously `use`ing it

2021-10-21 10:59 UTC, Adam-Gleave commented on bee-common/bee-common/src/logger/mod.rs
> +        use crate::time as time_util;
We'll have to import `crate::time::now_local` too, which seems ugly to me 😆

2021-10-21 11:01 UTC, thibault-martinez commented on bee-common/bee-common/src/logger/mod.rs
> +        use crate::time as time_util;
I don't particularly like it either but it's kinda convention to fully qualify paths inside macros... We also do that in other macros in the codebase

2021-10-21 11:02 UTC, thibault-martinez commented on bee-common/bee-common/src/logger/mod.rs
> +        use crate::time as time_util;
Feel free to keep the conditional use if you really prefer it ofc, just suggesting :)

2021-10-21 11:02 UTC, Adam-Gleave commented on bee-common/bee-common/src/logger/mod.rs
> +        use crate::time as time_util;
Ah sure, didn't realise that!

2021-10-21 11:15 UTC, thibault-martinez commented on bee-ledger/src/workers/snapshot/worker.rs
> +                time::format(&time::from_unix_timestamp(info.timestamp() as i64)),
Maybe a function `time::format_unix_timestamp` or similar as it seems like a frequent use case ?

2021-10-21 11:28 UTC, Adam-Gleave commented on bee-ledger/src/workers/snapshot/worker.rs
> +                time::format(&time::from_unix_timestamp(info.timestamp() as i64)),
Yeah, I think that might be helpful -- I'll add it.

2021-10-21 13:14 UTC, thibault-martinez commented on bee-ledger/src/workers/snapshot/worker.rs
> +                time::format(&time::from_unix_timestamp(info.timestamp() as i64)),
Use the newly created function ?

2021-10-21 13:23 UTC, thibault-martinez approved these changes

2021-10-21 14:01 UTC, merged