Make `bee-storage-sled` batches atomic.
iotaledger/bee pull request #790
Opened 2021-10-21 20:41 UTC by pvdrz

2021-10-25 15:57 UTC, thibault-martinez commented on bee-storage/bee-storage-sled/src/access/batch.rs
> +            .collect::<Result<Vec<_>, _>>()?;
Do we really have to collect this ? Can't we just iter in the transaction ?

2021-10-25 16:05 UTC, thibault-martinez commented on bee-storage/bee-storage-sled/src/access/batch.rs
> +            .collect::<Result<Vec<_>, _>>()?;
Ah, I didn't see it was used twice and once `as_slice`, don't mind me

2021-10-25 16:13 UTC, thibault-martinez requested changes

2021-10-25 16:13 UTC, thibault-martinez commented on bee-storage/bee-storage-sled/src/access/batch.rs
> +                TransactionError::Abort(_) => unreachable!(),
Can you put a comment why it's unreachable please ?

2021-10-25 18:01 UTC, samuel-rufi approved these changes

2021-10-26 09:50 UTC, Alex6323 approved these changes

2021-10-26 10:18 UTC, thibault-martinez approved these changes

2021-10-26 10:19 UTC, merged