Docs/add test build action
iotaledger/bee pull request #988
Opened 2022-01-19 14:05 UTC by lucas-tortora

# Description of change

As any build error in the docs can stop the wiki from updating, I've added a `test build` action to catch these before they are merged into the published branches, in this case `dev`

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix

## How the change has been tested

The action was tested in my fork for both passing and failure.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works

2022-01-19 14:06 UTC, lucas-tortora commented
@Dr-Electron, could you please review this when you have some time? Thanks!

2022-01-19 21:58 UTC, Dr-Electron submitted a review, later dismissed

2022-01-19 21:58 UTC, Dr-Electron commented
lgtm. But why don't we use the iota-wiki-cli anymore?

2022-01-20 06:49 UTC, grtlr requested changes
Thanks for submitting the PR! What do you think about it @thibault-martinez? I also left a couple of minor comments.

2022-01-20 06:49 UTC, grtlr commented on .github/workflows/test-docs-build.yml
> +  workflow_dispatch:
Since it's empty we could remove this.

```suggestion
```

2022-01-20 06:49 UTC, grtlr commented on .github/workflows/test-docs-build.yml
> +          if [ -e package-lock.json ]; then
Maybe we should always have a `package-lock.json` for reproducibility? In that case the check would be unnecessary.

2022-01-20 06:49 UTC, grtlr commented on .github/workflows/test-docs-build.yml
> +          yarn
Why is `yarn` mixed with `npm`?

2022-01-20 06:49 UTC, grtlr commented on .github/workflows/test-docs-build.yml
> +          npm i
Personally, I prefer the long form of these commands because it helps to document the code.

2022-01-20 06:49 UTC, grtlr commented on .github/workflows/test-docs-build.yml
> +          perl -0pe 's#$ENV{replace_string}#$ENV{config}#' docusaurus.config.js > docusaurus.config.js.cpy
It would be great if these steps would be documented a little bit using comments.

2022-01-20 13:18 UTC, lucas-tortora commented
> lgtm. But why don't we use the iota-wiki-cli anymore?

We are, but the way it's set up the process doesn't exit on error.  So it's not useful in this particular scenario.

2022-01-20 13:21 UTC, lucas-tortora commented on .github/workflows/test-docs-build.yml
> +          yarn
The iota-wiki-cli is installed with npm.  This is used to clone an instance of the iota-wiki, which uses docusarus, which uses yarn.  If there's a better/less confusing way to do this we could modify the script.

2022-01-20 13:23 UTC, lucas-tortora commented on .github/workflows/test-docs-build.yml
> +          npm i
Is there a long form for `npm ci`?

2022-01-20 13:39 UTC, thibault-martinez commented on .github/workflows/test-docs-build.yml
> +    if: github.event_name == 'pull_request'
Out of curiosity, is this necessary since we already have a `on.pull_request` ?

2022-01-20 13:42 UTC, Dr-Electron commented
> > lgtm. But why don't we use the iota-wiki-cli anymore?
> 
> We are, but the way it's set up the process doesn't exit on error. So it's not useful in this particular scenario.

I don't fully remember the code of the cli, but couldn't we change that? That way also locally you can du a quick check without running everything? Would that make sense?

2022-01-20 13:44 UTC, lucas-tortora commented
> > > lgtm. But why don't we use the iota-wiki-cli anymore?
> > 
> > 
> > We are, but the way it's set up the process doesn't exit on error. So it's not useful in this particular scenario.
> 
> I don't fully remember the code of the cli, but couldn't we change that? That way also locally you can du a quick check without running everything? Would that make sense?

I don't really know how to do that, but if it's possible I'd be 100% onboard.  It would make everything simpler and tidier.

2022-01-20 13:46 UTC, Dr-Electron commented
I can think about it this weekend. We can still merge this in the meantime. Don't know when I have the time to look at it. Already wanted to do that a long time ago 😅

2022-01-20 13:48 UTC, lucas-tortora commented
> I can think about it this weekend. We can still merge this in the meantime. Don't know when I have the time to look at it. Already wanted to do that a long time ago sweat_smile

We had added a test method already, I hope it helps.  We would just need to find a way for the gh action to know if it failed or not.

2022-01-20 13:52 UTC, Dr-Electron commented
> > I can think about it this weekend. We can still merge this in the meantime. Don't know when I have the time to look at it. Already wanted to do that a long time ago sweat_smile
> 
> We had added a test method already, I hope it helps. We would just need to find a way for the gh action to know if it failed or not.

I know. That's exactly what I wanted to work on... I just never find the time 😆

2022-01-20 15:38 UTC, grtlr commented on .github/workflows/test-docs-build.yml
> +          npm i
Sorry, it's been a while since I last used `npm`. `npm ci` is fine, of course.

2022-01-20 15:39 UTC, grtlr commented on .github/workflows/test-docs-build.yml
> +          yarn
Ok, cool. Thanks for clearing that up!

2022-01-20 16:41 UTC, thibault-martinez approved these changes

2022-01-20 16:57 UTC, grtlr approved these changes

2022-01-20 16:58 UTC, pvdrz approved these changes

2022-01-20 17:03 UTC, merged